(define
  (conf-frac n d k)
  (define
    (f i)
    (if (= i k)
      (/ (n i) (d i))
      (/ (n i) (+ (d i) (f (+ i 1))))
    )
  )
  (f 1)
)

(define (tan-cf x k)
  (define (n i) (if (= i 1) x (- (square x))))
  (define (d i) (- (* 2 i) 1))
  (conf-frac n d k)
)
(tan-cf 1 1)
(tan-cf 2 1)
(tan-cf 1 2)
(tan-cf 2 2)
